<?php namespace TheAnh\Post;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
